import Navbar from "@/components/global/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="fixed bottom-2 lg:botton-8 w-full overflow-hidden z-50">
          <Navbar />
        </nav>

        

        <main className="h-[100hv-200px]">{children}</main>
      </body>
    </html>
  );
}
